In [1]:
import pandas as pd
import sys

sys.path.insert(0, "..")

from src.feat import (
    fe_build_feature_table
)

In [2]:
source = "../data/processed/asthma_preprocessed.csv"

In [3]:
df = pd.read_csv(source)
df

,Age,BMI,PhysicalActivity,DietQuality,SleepQuality,PollutionExposure,PollenExposure,DustExposure,LungFunctionFEV1,LungFunctionFVC,...,Eczema,HayFever,GastroesophagealReflux,Wheezing,ShortnessOfBreath,ChestTightness,Coughing,NighttimeSymptoms,ExerciseInduced,Diagnosis
0,0.965740,-1.582769,-1.432099,0.160113,0.971063,0.809355,-0.780866,-1.401921,-1.368934,0.920608,...,0,0,0,0,0,1,0,0,1,0
1,-0.747054,-0.623300,0.291269,0.453069,-1.076746,-1.036866,0.810184,0.560684,-0.407132,-1.564256,...,0,0,0,1,0,0,1,1,1,0
2,0.687989,-1.229074,0.581330,1.434458,-0.102976,-1.210374,-1.267434,0.162295,-0.987146,0.983019,...,0,1,0,1,1,1,0,1,1,0
3,-0.098970,1.565307,-1.256398,0.276233,-1.596880,-1.509757,0.849659,-0.355611,0.561114,-1.105641,...,0,1,0,1,0,1,1,1,0,0
4,0.873156,-1.105686,-0.154081,-0.651625,1.504976,-1.373822,-0.713717,1.146977,1.070095,-0.516586,...,0,1,0,1,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,0.039905,0.252042,-0.699950,0.376978,0.740107,-0.861740,0.760717,-0.544470,0.669296,1.093099,...,0,0,0,0,1,0,0,0,1,1
2388,-1.117388,-0.903322,0.259526,-0.218561,0.411163,0.927074,-0.980178,0.519779,-1.642920,1.356614,...,1,0,0,0,0,0,1,1,0,1
2389,0.549114,1.365905,-0.109067,1.096868,0.268175,-0.755772,-0.711873,1.574952,-1.001130,-0.302584,...,0,1,0,1,0,1,1,0,1,1
2390,0.178780,-0.527792,1.591768,0.804295,-0.174204,1.511361,0.898316,0.024327,1.082816,-1.555908,...,0,0,1,0,1,1,0,1,1,0
2391,-0.747054,0.121962,-1.184528,0.821487,0.862093,-0.606925,-0.428764,0.028844,-0.310983,-0.988161,...,0,0,0,1,1,0,0,1,0,0

In [4]:
TARGET = 'Diagnosis'

df_final, info = fe_build_feature_table(
    df,
    target=TARGET,
    code_cols=["Gender","Ethnicity","EducationLevel"],
    corr_threshold=0.98,       
    drop_first=False          
)

In [5]:
print("Final shape:", df_final.shape)

for k, v in info.items():
    print(k, ":", v if isinstance(v, list) else v)

Final shape: (2392, 56)
added_by_composites : ['AtopyIndex', 'ExposureIndex', 'LungFunctionDiff', 'LungFunctionMin', 'RespiratorySymptomCount', 'SymptomCount']
added_by_interactions : ['BMI__x__PhysicalActivity', 'ExerciseInduced__x__Wheezing', 'GastroesophagealReflux__x__Age', 'GastroesophagealReflux__x__BMI', 'GastroesophagealReflux__x__DietQuality', 'GastroesophagealReflux__x__DustExposure', 'GastroesophagealReflux__x__LungFunctionFEV1', 'GastroesophagealReflux__x__LungFunctionFVC', 'GastroesophagealReflux__x__PhysicalActivity', 'GastroesophagealReflux__x__PollenExposure', 'GastroesophagealReflux__x__PollutionExposure', 'GastroesophagealReflux__x__SleepQuality', 'HistoryOfAllergies__x__HayFever', 'LungFunctionFEV1__x__LungFunctionFVC', 'PollutionExposure__x__PollenExposure', 'ShortnessOfBreath__x__ChestTightness', 'Wheezing__x__NighttimeSymptoms']
one_hot_new_cols : ['Gender=0', 'Gender=1', 'Ethnicity=0', 'Ethnicity=1', 'Ethnicity=2', 'Ethnicity=3', 'EducationLevel=0', 'EducationLevel=1', 'EducationLevel=2', 'EducationLevel=3']
dropped_zero_var : []
dropped_high_corr : ['Gender=1']

In [6]:
df_final.columns

Index(['Age', 'BMI', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure',
       'LungFunctionFEV1', 'LungFunctionFVC', 'Smoking', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'Wheezing', 'ShortnessOfBreath',
       'ChestTightness', 'Coughing', 'NighttimeSymptoms', 'ExerciseInduced',
       'RespiratorySymptomCount', 'AtopyIndex', 'ExposureIndex',
       'LungFunctionDiff', 'LungFunctionMin', 'SymptomCount',
       'ExerciseInduced__x__Wheezing', 'Wheezing__x__NighttimeSymptoms',
       'ShortnessOfBreath__x__ChestTightness',
       'HistoryOfAllergies__x__HayFever',
       'GastroesophagealReflux__x__PollutionExposure',
       'GastroesophagealReflux__x__PollenExposure',
       'GastroesophagealReflux__x__DustExposure',
       'GastroesophagealReflux__x__BMI', 'GastroesophagealReflux__x__Age',
       'GastroesophagealReflux__x__LungFunctionFEV1',
       'GastroesophagealReflux__x__LungFunctionFVC',
       'GastroesophagealReflux__x__PhysicalActivity',
       'GastroesophagealReflux__x__DietQuality',
       'GastroesophagealReflux__x__SleepQuality',
       'PollutionExposure__x__PollenExposure',
       'LungFunctionFEV1__x__LungFunctionFVC', 'BMI__x__PhysicalActivity',
       'Gender=0', 'Ethnicity=0', 'Ethnicity=1', 'Ethnicity=2', 'Ethnicity=3',
       'EducationLevel=0', 'EducationLevel=1', 'EducationLevel=2',
       'EducationLevel=3', 'Diagnosis'],
      dtype='object')

In [7]:
df_final.head(3)

,Age,BMI,PhysicalActivity,DietQuality,SleepQuality,PollutionExposure,PollenExposure,DustExposure,LungFunctionFEV1,LungFunctionFVC,...,Gender=0,Ethnicity=0,Ethnicity=1,Ethnicity=2,Ethnicity=3,EducationLevel=0,EducationLevel=1,EducationLevel=2,EducationLevel=3,Diagnosis
0,0.965740,-1.582769,-1.432099,0.160113,0.971063,0.809355,-0.780866,-1.401921,-1.368934,0.920608,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0
1,-0.747054,-0.623300,0.291269,0.453069,-1.076746,-1.036866,0.810184,0.560684,-0.407132,-1.564256,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0
2,0.687989,-1.229074,0.581330,1.434458,-0.102976,-1.210374,-1.267434,0.162295,-0.987146,0.983019,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0

In [8]:
df_final.dtypes

Age                                             float64
BMI                                             float64
PhysicalActivity                                float64
DietQuality                                     float64
SleepQuality                                    float64
PollutionExposure                               float64
PollenExposure                                  float64
DustExposure                                    float64
LungFunctionFEV1                                float64
LungFunctionFVC                                 float64
Smoking                                         float64
PetAllergy                                      float64
FamilyHistoryAsthma                             float64
HistoryOfAllergies                              float64
Eczema                                          float64
HayFever                                        float64
GastroesophagealReflux                          float64
Wheezing                                        float64
ShortnessOfBreath                               float64
ChestTightness                                  float64
Coughing                                        float64
NighttimeSymptoms                               float64
ExerciseInduced                                 float64
RespiratorySymptomCount                         float64
AtopyIndex                                      float64
ExposureIndex                                   float64
LungFunctionDiff                                float64
LungFunctionMin                                 float64
SymptomCount                                    float64
ExerciseInduced__x__Wheezing                    float64
Wheezing__x__NighttimeSymptoms                  float64
ShortnessOfBreath__x__ChestTightness            float64
HistoryOfAllergies__x__HayFever                 float64
GastroesophagealReflux__x__PollutionExposure    float64
GastroesophagealReflux__x__PollenExposure       float64
GastroesophagealReflux__x__DustExposure         float64
GastroesophagealReflux__x__BMI                  float64
GastroesophagealReflux__x__Age                  float64
GastroesophagealReflux__x__LungFunctionFEV1     float64
GastroesophagealReflux__x__LungFunctionFVC      float64
GastroesophagealReflux__x__PhysicalActivity     float64
GastroesophagealReflux__x__DietQuality          float64
GastroesophagealReflux__x__SleepQuality         float64
PollutionExposure__x__PollenExposure            float64
LungFunctionFEV1__x__LungFunctionFVC            float64
BMI__x__PhysicalActivity                        float64
Gender=0                                        float64
Ethnicity=0                                     float64
Ethnicity=1                                     float64
Ethnicity=2                                     float64
Ethnicity=3                                     float64
EducationLevel=0                                float64
EducationLevel=1                                float64
EducationLevel=2                                float64
EducationLevel=3                                float64
Diagnosis                                         int64
dtype: object

In [9]:
print("Any NaNs?", df_final.isna().any().any())

Any NaNs? False

In [10]:
out_dir = "../data/processed"

In [11]:
df_final.to_csv(out_dir + "/asthma_features.csv", index=False)

In [12]:
print("Saved FE dataset to:", out_dir + "/asthma_features.csv")

Saved FE dataset to: ../data/processed/asthma_features.csv